export const labs = [
    {
        id: 'analises_clinicas',
        name: 'Análises Clínicas',
        icon: 'test-tube-2',
        description: 'Diagnósticos biológicos, hematológicos e ensaios químicos de rotina.',
        items: [
            { 
                name: 'Agitador Magnético com Aquecimento', 
                brand: 'GLOBAL TRADE', 
                model: 'GT-AMB 10L', 
                supplier: 'E-LABCOMMERCE LTDA', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Preparo', 
                icon: 'rotate-cw', 
                pdfUrl: 'pdfs/POP_AGITADOR_MAGNETICO_COM_AQUECIMENTO.pdf', 
                procedure: '1. Coloque o frasco com barra magnética limpa sobre a plataforma.\n2. Ligue o interruptor geral na parte traseira/lateral.\n3. Ajuste a velocidade de agitação gradualmente no sentido horário.\n4. Ajuste a temperatura desejada, se necessário, monitorando o LED.\n5. Use volume reduzido para líquidos viscosos para evitar travamento.\n6. Após o uso, reduza os controles a zero e aguarde resfriamento para limpeza.' 
            },
            { 
                name: 'Autoclave Vertical', 
                brand: 'PHOENIX', 
                model: 'AV 100L', 
                supplier: 'PHOENIX Indústria', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Esterilização', 
                icon: 'database', 
                pdfUrl: 'pdfs/POP_AUTOCLAVE_VERTICAL.pdf', 
                procedure: '1. Abasteça com água destilada até cobrir a resistência.\n2. Coloque os materiais nos cestos e feche os manípulos em cruz.\n3. Abra a válvula de purga e ligue no CALOR MÁXIMO.\n4. Feche a purga após saída constante de vapor e mude para MÉDIO.\n5. Inicie a contagem do tempo após atingir a pressão de trabalho.\n6. Ao final, desligue e libere o vapor; abra apenas com pressão zero.' 
            },
            { 
                name: 'Balança Semi-Analítica', 
                brand: 'BEL Engineering', 
                model: 'MARK M 4202', 
                supplier: 'BEL ENGINEERING', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Pesagem', 
                icon: 'scale', 
                pdfUrl: 'pdfs/POP_BALANCA_SEMI_ANALITICA.pdf', 
                procedure: '1. Verifique o nivelamento da balança através da bolha de nível.\n2. Ligue o equipamento e aguarde 30 min para estabilização térmica.\n3. Execute a calibração (CAL) se houver variação ambiental.\n4. Utilize um recipiente de pesagem e pressione TARA para zerar.\n5. Adicione a amostra no centro do prato e aguarde a leitura estável.\n6. Limpe o prato com pincel macio e desligue após o uso.' 
            },
            { 
                name: 'Banho Maria', 
                brand: 'SOLAB', 
                model: 'SL-150/28', 
                supplier: 'Solab Científica', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Aquecimento', 
                icon: 'thermometer', 
                pdfUrl: 'pdfs/POP_BANHO_MARIA.pdf', 
                procedure: '1. Preencha a cuba com água destilada até cobrir a resistência.\n2. Ligue o aparelho na chave geral e ajuste a temperatura (setpoint).\n3. Pressione a tecla "F" para salvar a temperatura selecionada.\n4. Aguarde a estabilização térmica antes de inserir as amostras.\n5. Monitore o nível de água para evitar exposição da resistência.\n6. Drene a água pela válvula traseira periodicamente para higienização.' 
            },
            { 
                name: 'Cabine de Fluxo Laminar (NF4703)', 
                brand: 'BSTEC', 
                model: 'NF4703', 
                supplier: 'BS TEC', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Microbiologia', 
                icon: 'wind', 
                pdfUrl: 'pdfs/POP_CABINE_DE_FLUXO_LAMINAR_NF4703.pdf', 
                procedure: '1. Ligue a luz Germicida (UV) por 15 min antes do uso (sem amostras}.\n2. Desligue a UV e ligue o exaustor e luz branca por 5 min.\n3. Sanitização interna com álcool 70% em toda a área de trabalho.\n4. Organize materiais a 10cm do vidro frontal para não obstruir o fluxo.\n5. Não utilize bico de bunsen ou chamas no interior da cabine.\n6. Realize a limpeza completa semanalmente com detergente neutro.' 
            },
            { 
                name: 'Capela de Fluxo Laminar (S27)', 
                brand: 'BSTEC', 
                model: 'S27', 
                supplier: 'BS TEC', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Microbiologia', 
                icon: 'wind', 
                pdfUrl: 'pdfs/POP_CAPELA_DE_FLUXO_LAMINAR_S27.pdf', 
                procedure: '1. Ative a luz UV por 20 min com o vidro frontal fechado.\n2. Ligue o motor de exaustão e aguarde a estabilização do fluxo.\n3. Higienize as superfícies internas com álcool 70%.\n4. Trabalhe sempre no centro da área, longe das bordas.\n5. Desligue tudo após o uso e higienize novamente.\n6. Manutenção dos filtros HEPA deve ser feita anualmente por técnico.' 
            },
            { 
                name: 'Centrífuga Clínica Digital', 
                brand: 'CENTRILAB', 
                model: 'CE 3001', 
                supplier: 'Global Trade Technology', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Hematologia', 
                icon: 'loader-pinwheel', 
                pdfUrl: 'pdfs/POP_CENTRIFUGA_CLINICA_DIGITAL.pdf', 
                procedure: '1. Verifique se as porcas no rotor estão apertadas antes do uso.\n2. Distribua os tubos simetricamente no rotor para equilíbrio.\n3. Feche a tampa e trave o mecanismo de segurança.\n4. Programe a velocidade (RPM) e o tempo conforme o protocolo.\n5. Acione a partida e monitore por vibrações anômalas.\n6. Aguarde a parada completa e sinal sonoro antes de abrir.' 
            },
            { 
                name: 'Centrífuga Manual', 
                brand: 'Manual S.A.', 
                model: 'C-MANUAL', 
                supplier: 'LabSupplies', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Hematologia', 
                icon: 'rotate-cw', 
                pdfUrl: 'pdfs/POP_CENTRIFUGA_MANUAL.pdf', 
                procedure: '1. Insira os tubos de ensaio com volumes idênticos em oposição.\n2. Fixe a centrífuga firmemente na borda da bancada.\n3. Gire a manivela aplicando força constante e gradual.\n4. Mantenha a rotação pelo tempo determinado no ensaio.\n5. Reduza a força gradualmente; nunca pare o rotor com as mãos.\n6. Retire os tubos com cuidado para preservar o sedimento.' 
            },
            { 
                name: 'Destilador de Água', 
                brand: 'SOLID STEEL', 
                model: 'SSDEST 10L/H', 
                supplier: 'Solisteel Comércio', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Setor de Águas', 
                icon: 'droplet', 
                pdfUrl: 'pdfs/POP_DESTILADOR_DE_AGUA.pdf', 
                procedure: '1. Verifique se o equipamento está nivelado e o dreno fechado.\n2. Abra o registro de entrada de água até completar a caldeira.\n3. Ligue o aquecimento geral; aguarde a ebulição e destilação.\n4. Monitore o fluxo de água de refrigeração para evitar superaquecimento.\n5. Ao desligar, mantenha a água aberta por 2 min para resfriar.\n6. Realize limpeza química mensal com vinagre para desincrustar.' 
            },
            { 
                name: 'Espectrofotômetro Digital', 
                brand: 'NOVA', 
                model: 'NI 2000', 
                supplier: 'Nova Instruments', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Bioquímica', 
                icon: 'waves', 
                pdfUrl: 'pdfs/POP_ESPECTROFOTOMETRO_DIGITAL.pdf', 
                procedure: '1. Ligue o aparelho e aguarde 20 min para estabilizar a lâmpada.\n2. Selecione o comprimento de onda (λ) usando as teclas GOTO.\n3. Insira a cubeta com o branco e pressione ZERO para calibrar.\n4. Realize a leitura das amostras inserindo-as na célula detentora.\n5. Cubetas devem ser manuseadas pelas faces foscas e limpas.\n6. Feche a tampa do compartimento óptico durante cada leitura.' 
            },
            { 
                name: 'Estufa de Cultura Bacteriológica', 
                brand: 'SP Labor', 
                model: 'SP-200', 
                supplier: 'SP Labor LTDA', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Incubação', 
                icon: 'box', 
                pdfUrl: 'pdfs/POP_ESTUFA_DE_CULTURA_BACTERIOLOGICA.pdf', 
                procedure: '1. Ajuste a temperatura de trabalho (Set Point) no controlador.\n2. Configure o termostato de segurança 2 graus acima do SP.\n3. Distribua as placas/tubos com espaço para circulação de ar.\n4. Evite manter a porta aberta por longos períodos para manter a estabilidade.\n5. Monitore a temperatura diariamente através do termômetro de porta.\n6. Higienize as prateleiras com álcool 70% mensalmente.' 
            },
            { 
                name: 'Estufa de Secagem', 
                brand: 'BIOPAR', 
                model: 'S150ST', 
                supplier: 'Biopar Equipamentos', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Lavagem/Secagem', 
                icon: 'sun', 
                pdfUrl: 'pdfs/POP_ESTUFA_DE_SECAGEM.pdf', 
                procedure: '1. Pré-aqueça a estufa até a temperatura desejada antes da carga.\n2. Coloque as vidrarias limpas de forma organizada nas prateleiras.\n3. Mantenha os respiros superiores levemente abertos para saída de umidade.\n4. Para esterilização, mantenha 170°C por 2 horas constantes.\n5. Desligue e aguarde o resfriamento natural antes de abrir a porta.\n6. Use luvas térmicas para manipular materiais aquecidos.' 
            },
            { 
                name: 'Forno de Microondas', 
                brand: 'ELECTROLUX', 
                model: 'MEF41', 
                supplier: 'Electrolux da Amazônia Ltda', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Copa/Lab', 
                icon: 'box', 
                pdfUrl: 'pdfs/POP_FORNO_DE_MICROONDAS.pdf', 
                procedure: '1. Utilize apenas recipientes de vidro ou plástico compatíveis.\n2. Nunca introduza objetos metálicos ou papel alumínio.\n3. Regule o tempo e a potência conforme o volume do líquido/meio.\n4. Mantenha a porta fechada durante todo o funcionamento.\n5. Limpeza interna após cada uso com pano úmido e sabão neutro.\n6. Verifique periodicamente a integridade da vedação da porta.' 
            },
            { 
                name: 'Incubadora Shaker', 
                brand: 'LUCADEMA', 
                model: 'LUCA-222', 
                supplier: 'Lucadema Soluções', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Biotecnologia', 
                icon: 'flask-conical', 
                pdfUrl: 'pdfs/POP_INCUBADORA_SHAKER.pdf', 
                procedure: '1. Fixe os frascos Erlenmeyer firmemente nas garras da plataforma.\n2. Programe a temperatura e a rotação (RPM) no painel digital.\n3. Acione o botão de agitação e o aquecimento de forma independente.\n4. Feche a tampa acrílica para evitar perda de calor e ruído.\n5. Ao término, reduza a rotação e aguarde estabilização para abrir.\n6. Limpe a plataforma com pano úmido após o resfriamento.' 
            },
            { 
                name: 'Seladora a Vácuo', 
                brand: 'CETRO', 
                model: 'P-280', 
                supplier: 'Cetro Máquinas', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Setor de Insumos', 
                icon: 'shrink', 
                pdfUrl: 'pdfs/POP_SELADORA_A_VACUO.pdf', 
                procedure: '1. Alinhe o saco plástico na barra de sucção de forma centralizada.\n2. Feche a tampa e pressione as travas laterais até o travamento.\n3. Ajuste o tempo de selagem conforme a gramatura do plástico.\n4. Inicie o processo de sucção; a selagem ocorre automaticamente.\n5. Aguarde o bip sonoro e libere as travas para retirada.\n6. Não utilize com líquidos que possam ser aspirados para a bomba.' 
            },
            { 
                name: 'Ultrafreezer', 
                brand: 'THERMOTEMP', 
                model: 'Vertical', 
                supplier: 'BS Tec Soluções', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Criogenia', 
                icon: 'snowflake', 
                pdfUrl: 'pdfs/POP_ULTRAFREEZER.pdf', 
                procedure: '1. Mantenha o Set Point entre -40°C e -86°C conforme especificado.\n2. Utilize racks metálicos para organizar e identificar as caixas.\n3. Minimize o tempo de porta aberta (máximo 30 segundos por vez).\n4. Verifique a vedação da porta externa contra formação de gelo.\n5. Limpeza do condensador (filtro) deve ser feita mensalmente.\n6. Caso o alarme soe, verifique a vedação ou falha de energia imediatamente.' 
            },
            { 
                name: 'Ultrapurificador de Água', 
                brand: 'GEHAKA', 
                model: 'MS 3000', 
                supplier: 'Gehaka LTDA', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Aguas Especiais', 
                icon: 'filter', 
                pdfUrl: 'pdfs/POP_ULTRAPURIFICADOR_DE_AGUA.pdf', 
                procedure: '1. Certifique-se de que o registro da água de entrada está aberto.\n2. Ligue o sistema e monitore o valor de condutividade no display.\n3. Dispense a água através do gatilho ou programação de volume.\n4. Descarte os primeiros 100ml de cada manhã para limpar a via.\n5. Troque as colunas/filtros quando indicado pelo alerta sonoro.\n6. Realize sanitização sistêmica anual conforme manual técnico.' 
            }
        ]
    },
    {
        id: 'lavagem',
        name: 'Biossegurança',
        icon: 'shield-check',
        description: 'Padrões de higiene e segurança física nos laboratórios.',
        items: [
            { 
                name: 'Higienização das Mãos', 
                brand: 'IFTO', 
                model: 'POP.IFTO 001', 
                supplier: 'Biossegurança', 
                emission: '23/02/2026', 
                revision: '--', 
                location: 'Geral', 
                icon: 'hand', 
                pdfUrl: 'pdfs/POP_HIGIENIZACAO_DAS_MAOS.pdf',
                procedure: '1. Molhe as mãos e aplique sabão líquido cobrindo as superfícies.\n2. Friccione palmas, dorso, entre os dedos e polegares (40-60s).\n3. Enxágue abundantemente retirando todo o resíduo de sabão.\n4. Seque com papel toalha descartável iniciando pelas mãos.\n5. Utilize o papel para fechar a torneira e descarte adequadamente.\n6. Use álcool 70% apenas quando as mãos estiverem visualmente limpas.', 
                tables:[{title:"Resumo de Tempo", headers:["Método", "Duração"], rows:[["Lavagem", "40-60 Segundos"], ["Antissepsia (Álcool)", "20-30 Segundos"]]}] 
            },
            { 
                name: 'Lavagem de Vidrarias', 
                brand: 'IFTO', 
                model: 'POP.IFTO 002', 
                supplier: 'S. Lavagem', 
                emission: '23/02/2026', 
                revision: '--', 
                location: 'DML', 
                icon: 'glass-water', 
                pdfUrl: 'pdfs/POP_LAVAGEM_DE_VIDRARIAS.pdf',
                procedure: '1. Descarte resíduos químicos ou biológicos em local apropriado.\n2. Realize pré-lavagem com água corrente e esponja macia.\n3. Deixe imerso em solução de detergente tensoativo por 20 min.\n4. Enxágue exaustivamente sob água corrente (mínimo 3 vezes).\n5. Realize banho final com água destilada ou deionizada.\n6. Encaminhe para secagem em estufa a 60°C ou temperatura ambiente.', 
                tables:[{title:"Etapas do Fluxo", headers:["Fase", "Ação", "Finalidade"], rows:[["I", "Triagem", "Descarte correto"], ["II", "Ação Química", "Remoção de gordura"], ["III", "Acabamento", "Pureza da superfície"], ["IV", "Descontaminação", "Secagem segura"]]}] 
            },
            { 
                name: 'Limpeza de Bancada', 
                brand: 'IFTO', 
                model: 'POP.IFTO 003', 
                supplier: 'IFTO', 
                emission: '16/05/2026', 
                revision: '16/05/2028', 
                location: 'Geral', 
                icon: 'armchair', 
                pdfUrl: 'pdfs/POP_LIMPEZA_DE_BANCADA.pdf',
                procedure: '1. Libere a bancada removendo materiais e equipamentos portáteis.\n2. Aplique álcool 70% com borrifador em toda a superfície.\n3. Passe o pano em movimento unidirecional de fundo para frente.\n4. Aguarde a secagem completa antes de retornar as atividades.\n5. Em caso de derramamento biológico, use hipoclorito a 1%.\n6. Execute a rotina no início e término de cada prática laboratorial.' 
            },
            { 
                name: 'Lava-Olhos', 
                brand: 'GENEBRE', 
                model: 'EPC-101', 
                supplier: 'Genebre Brasil', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Geral', 
                icon: 'eye', 
                pdfUrl: 'pdfs/POP_LAVA_OLHOS.pdf',
                procedure: '1. Em caso de acidente, ative a alça manual ou pedal de acionamento.\n2. Posicione os olhos abertos sob as bicas de saída de água.\n3. Utilize os dedos para manter as pálpebras abertas durante o fluxo.\n4. Lave por no mínimo 15 minutos ininterruptos.\n5. Remova lentes de contato se o acidente envolver produtos químicos.\n6. Procure atendimento médico urgente após a lavagem de emergência.' 
            }
        ]
    },
    {
        id: 'microscopia',
        name: 'Microscopia',
        icon: 'search',
        description: 'Setor de análise morfológica e diagnóstico citopatológico.',
        items: [
            { 
                name: 'Contador de Células Sanguíneas', 
                brand: 'KACIL', 
                model: 'CCS 02', 
                supplier: 'Kacil Indústria', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Hematologia', 
                icon: 'calculator', 
                pdfUrl: 'pdfs/POP_CONTADOR_DE_CELULAS_SANGUINEAS.pdf', 
                procedure: '1. Ligue e verifique se o visor marca "ZERO" no canto direito.\n2. Selecione a função LEUCOCITÁRIO ou HEMÁCIAS no painel.\n3. Utilize as 10 teclas para contagem de tipos celulares diversos.\n4. O alarme soará ao atingir 100 células (bloqueio automático).\n5. Para índices hematimétricos, insira os valores de HB/HT via teclas.\n6. Realize a limpeza externa e da sonda de sucção ao final do dia.', 
                tables:[{title:"Índices Automáticos", headers:["Sigla", "Descrição"], rows:[["VCM", "Volume Corpuscular Médio"], ["HCM", "Hemoglobina Corpuscular Média"], ["CHCM", "Conc. Hemoglobina Corp. Média"]]}] 
            },
            { 
                name: 'Microscópio Estereoscópio', 
                brand: 'BIOFOCUS', 
                model: 'Stereo-X', 
                supplier: 'Ionlab', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Bancada Principal', 
                icon: 'microscope', 
                pdfUrl: 'pdfs/POP_MICROSCOPIO_ESTEREOSCOPIO.pdf', 
                procedure: '1. Posicione a amostra sobre a platina central e ligue a luz.\n2. Ajuste a distância interpupilar movendo as oculares laterais.\n3. Utilize o botão macrométrico para o foco inicial da imagem.\n4. Selecione o aumento desejado girando o revólver de zoom.\n5. Ajuste a dioptria na ocular esquerda para nitidez fina.\n6. Limpe as lentes apenas com papel óptico de seda e solução neutra.' 
            },
            { 
                name: 'Microscópio Óptico', 
                brand: 'BIOFOCUS', 
                model: 'Infinita', 
                supplier: 'Ionlab', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Bancada Principal', 
                icon: 'microscope', 
                pdfUrl: 'pdfs/POP_MICROSCOPIO_OPTICO.pdf', 
                procedure: '1. Ligue a lâmpada e inicie o foco com a objetiva de 4X.\n2. Centralize a lâmina e utilize o macrométrico para imagem geral.\n3. Para 10X e 40X, utilize apenas o botão micrométrico (foco fino).\n4. Para 100X, adicione uma gota de óleo de imersão sobre a lâmina.\n5. Nunca use o macrométrico na objetiva de 100X (risco de quebra).\n6. Limpe a objetiva de 100X com álcool-cetona (7:3) após cada uso.' 
            }
        ]
    },
    {
        id: 'multididatico',
        name: 'Multididático',
        icon: 'layers',
        description: 'Plataforma para bioprospecção, técnicas moleculares e ensino.',
        items: [
            { 
                name: 'Agitador Magnético com Aquecimento', 
                brand: 'GEHAKA', 
                model: 'AA-200', 
                supplier: 'Gehaka', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Geral', 
                icon: 'rotate-cw', 
                pdfUrl: 'pdfs/AGITADOR_MAGNETICO_COM_AQUECIMENTO.pdf', 
                procedure: '1. Coloque o frasco com barra magnética limpa no centro da placa.\n2. Ligue o motor e ajuste a velocidade gradualmente no seletor.\n3. Ajuste o controle de temperatura conforme a necessidade analítica.\n4. Use o sensor externo (PT100) para controle preciso da solução.\n5. Desligue o aquecimento e deixe a placa resfriar antes de mover ou limpar.\n6. Evite derramamento de líquidos diretamente sobre o painel de comando.' 
            },
            { 
                name: 'Balança Analítica', 
                brand: 'SHIMADZU', 
                model: 'ATX-R', 
                supplier: 'Shimadzu Brasil', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Pesagem Especial', 
                icon: 'scale-3d', 
                pdfUrl: 'pdfs/BALANLCA_ANALITICA.pdf', 
                procedure: '1. Certifique-se de que a balança está ligada há 30 min (warm-up).\n2. Feche todas as portas da capela e verifique se o prato está livre.\n3. Pressione a tecla "O/T" para realizar o zeramento.\n4. Insira o peso padrão ou amostra utilizando pinças de manipulação.\n5. Aguarde o indicador de estabilidade (*) para realizar a leitura.\n6. Limpe a câmara de pesagem com pincel macio após cada rotina.' 
            },
            { 
                name: 'Banho Ultrassônico Conjugado', 
                brand: 'SOLID STEEL', 
                model: 'SSBuc 10L', 
                supplier: 'Solisteel', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Limpeza', 
                icon: 'droplets', 
                pdfUrl: 'pdfs/BANHO_ULTRASSONICO_CONJUGADO.pdf', 
                procedure: '1. Coloque água na cuba até 3cm da borda superior.\n2. Adicione detergente enzimático se o objetivo for limpeza.\n3. Organize os materiais dentro do cesto perfurado (nunca no fundo).\n4. Ajuste o tempo desejado na tecla "ADJUST" e pressione "START".\n5. Ao sinal sonoro, remova o cesto e enxágue as peças em água corrente.\n6. Evazie a cuba pelo registro lateral e limpe internamente.' 
            },
            { 
                name: 'Banho Ultratermostatizado', 
                brand: 'QUIMIS', 
                model: 'Q214M', 
                supplier: 'Quimis', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Análises', 
                icon: 'thermometer', 
                pdfUrl: 'pdfs/BANHO_ULTRATERMOSTATIZADO.pdf', 
                procedure: '1. Abasteça a cuba com o fluido térmico (água ou óleo) indicado.\n2. Programe a temperatura de trabalho no controlador PID digital.\n3. Verifique se a bomba de circulação está ativa para homogeneidade.\n4. Aguarde a sinalização de temperatura atingida no visor (SV=PV).\n5. Ao término, reduza a temperatura para 0°C antes de desligar.\n6. Verifique periodicamente o nível do fluido para evitar queima da bomba.' 
            },
            { 
                name: 'Câmera Escura UV', 
                brand: 'CIENLAB', 
                model: 'CE-850-L', 
                supplier: 'Cienlab', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Bancada UV', 
                icon: 'scan', 
                pdfUrl: 'pdfs/CAMERA_ESCURA_UV.pdf', 
                procedure: '1. Conecte o cabo de rede e selecione a lâmpada (254nm ou 365nm).\n2. Abra a porta de correr e posicione a placa de gel centralizada.\n3. Feche completamente a porta antes de acionar a radiação UV.\n4. Utilize óculos de proteção UV certificados pelo laboratório.\n5. Não ultrapasse 5 min de exposição contínua sob pena de degradação.\n6. Realize limpeza interna com pano macio e álcool isopropílico.' 
            },
            { 
                name: 'Centrífuga', 
                brand: 'FANEM', 
                model: 'Baby I', 
                supplier: 'Fanem', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Geral', 
                icon: 'loader-pinwheel', 
                pdfUrl: 'pdfs/CENTRIFUGA.pdf', 
                procedure: '1. Verifique o balanceamento dos tubos (mesmo volume e pesos).\n2. Trave a tampa girando a manopla até o fim do curso.\n3. Selecione a velocidade RPM média no painel frontal.\n4. Ative o cronômetro para o tempo determinado na técnica.\n5. Aguarde o rotor parar completamente por inércia antes de abrir.\n6. Não tente abrir a tampa durante a rotação para evitar acidentes.' 
            },
            { 
                name: 'Destilador de Água', 
                brand: 'QUIMIS', 
                model: 'Q341', 
                supplier: 'Quimis', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Setor de Águas', 
                icon: 'droplet', 
                pdfUrl: 'pdfs/DESTILADOR_DE_AGUA.pdf', 
                procedure: '1. Conecte as mangueiras de entrada e saída conforme as marcações.\n2. Abra o registro de fluxo de água de refrigeração no nível médio.\n3. Ligue a chave de aquecimento; a produção inicia após 15 min.\n4. Descarte os primeiros litros cada vez que ligar o equipamento.\n5. Ao desligar, feche a água apenas após 5 min para resfriar a caldeira.\n6. Realize limpeza química com solução ácida a cada 15 dias.' 
            },
            { 
                name: 'Estufa de Cultura Bacteriológica', 
                brand: 'SOLAB', 
                model: 'SL-100', 
                supplier: 'Solab', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Microbiologia', 
                icon: 'box', 
                pdfUrl: 'pdfs/ESTUFA_DE_CULTURA_BACTERIOLOGICA.pdf', 
                procedure: '1. Programe a temperatura de incubação (ex: 37°C) no controlador.\n2. Verifique o termostato de segurança e trave a porta externa.\n3. Utilize prateleiras organizadas sem sobreposição de amostras.\n4. Realize a limpeza interna rigorosa com álcool 70% mensalmente.\n5. Monitore a estabilidade térmica através do display digital.\n6. Alerte o técnico caso haja variação superior a 1°C do setpoint.' 
            },
            { 
                name: 'Estufa Digital Esterilização e Secagem', 
                brand: 'SOLAB', 
                model: 'SL-102', 
                supplier: 'Solab', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Esterilização', 
                icon: 'sun', 
                pdfUrl: 'pdfs/ESTUFA_DIGITAL_ESTERILIZACAO_.pdf', 
                procedure: '1. Ajuste a temperatura (170°C) e pressione SET para confirmar.\n2. Coloque as maretiais/vidrarias secas dentro das bandejas.\n3. Inicie o ciclo de esterilização; aguarde 2 horas após estabilidade.\n4. O controlador bipará ao final; desligue e aguarde resfriamento.\n5. Não retire materiais com temperatura acima de 40°C.\n6. Verifique periodicamente a ventilação e integridade dos sensores.' 
            },
            { 
                name: 'Forno Mufla', 
                brand: 'QUIMIS', 
                model: 'Q318M', 
                supplier: 'Quimis', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Análises Térmicas', 
                icon: 'flame', 
                pdfUrl: 'pdfs/FORNO_MUFLA.pdf', 
                procedure: '1. Utilize apenas cadinhos cerâmicos secos dentro da câmara.\n2. Programe a rampa de aquecimento (vários passos se necessário).\n3. Utilize obrigatoriamente luvas térmicas e pinças de cabo longo.\n4. Feche a porta e aguarde atingir a temperatura (pode chegar a 1200°C).\n5. Não abra a porta enquanto a temperatura estiver acima de 500°C.\n6. Deixe o forno resfriar naturalmente; não use ventiladores externos.' 
            },
            { 
                name: 'Incubadora Shaker', 
                brand: 'SOLAB', 
                model: 'SL-221', 
                supplier: 'Solab', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Biotecnologia', 
                icon: 'flask-conical', 
                pdfUrl: 'pdfs/INCUBADORA_SHAKER.pdf', 
                procedure: '1. Fixe as garras ou racks na plataforma de forma balanceada.\n2. Programe a rotação (RPM) e temperatura no painel digital.\n3. Ative o timer para desligamento automático se necessário.\n4. Feche a porta hermeticamente para evitar fugas térmicas.\n5. Monitore ruídos anômalos que indiquem desbalanceamento.\n6. Realize limpeza semanal da plataforma externa e sensores.' 
            },
            { 
                name: 'Manta Aquecedora', 
                brand: 'FAITHFUL', 
                model: '125 mL', 
                supplier: 'Faithful Inst.', 
                emission: '23/02/2026', 
                revision: '--', 
                location: 'Química', 
                icon: 'flame', 
                pdfUrl: 'pdfs/MANTA_AQUECEDORA.pdf', 
                procedure: '1. Encaixe o balão de fundo redondo (125mL) no ninho da manta.\n2. Ligue o cabo de força e ajuste o potenciômetro lateral.\n3. Verifique se o LED de aquecimento (POWER) está aceso.\n4. Não ligue a manta vazia; risco de queima da resistência.\n5. Utilize sensor de temperatura para evitar superaquecimento do líquido.\n6. Desligue e aguarde o resfriamento total antes de guardar.' 
            },
            { 
                name: 'Micrótomo', 
                brand: 'LUPETEC', 
                model: 'MRP 2015', 
                supplier: 'Lupetec', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Histotecnologia', 
                icon: 'scissors', 
                pdfUrl: 'pdfs/MICROTOMO.pdf', 
                procedure: '1. Bloqueie o volante principal e instale o bloco de parafina.\n2. Encaixe a navalha descartável com o ângulo de ataque correto.\n3. Selecione a espessura do corte em mícrons (µm) no seletor.\n4. Destrave o volante e realize cortes firmes e constantes.\n5. Utilize o recuo automático para cortes seriados de precisão.\n6. Limpe os resíduos de parafina da bandeja e peças com pincel seco.' 
            },
            { 
                name: 'Seladora', 
                brand: 'CETRO', 
                model: 'S-300', 
                supplier: 'Cetro', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Insumos', 
                icon: 'shrink', 
                pdfUrl: 'pdfs/SELADORA.pdf', 
                procedure: '1. Ajuste o nível de calor no seletor graduado frontal.\n2. Posicione a embalagem entre as barras metálicas de selagem.\n3. Baixe a alça manual e mantenha pressionado até o sinal sonoro.\n4. Aguarde 2 segundos antes de abrir para garantir a aderência.\n5. Verifique se a solda está uniforme em toda a largura do plástico.\n6. Substitua a fita de proteção (Teflon) quando houver desgaste.' 
            },
            { 
                name: 'Viscosímetro', 
                brand: 'MARTE', 
                model: 'MVD-20', 
                supplier: 'Marte Científica', 
                emission: '08/07/2025', 
                revision: '08/07/2027', 
                location: 'Bioprospecção', 
                icon: 'droplets', 
                pdfUrl: 'pdfs/VISCOSIMETRO.pdf', 
                procedure: '1. Selecione o spindle (rotor) adequado à viscosidade estimada.\n2. Encaixe o spindle no motor e imirja até a marca na amostra.\n3. Programe o RPM no painel digital e acione o motor.\n4. Aguarde a estabilização da leitura de torque no visor LCD.\n5. Pressione a trava de leitura para fixar o valor da viscosidade.\n6. Remova o spindle e limpe-o imediatamente com solvente neutro.' 
            }
        ]
    }
];
